"use client";
import {useEffect,useRef,useState} from 'react';
import {Content,defaultContent,KEY} from '@/lib/content';

type Mode='home'|'face'|'finger';
export default function Home(){
 const [content,setContent]=useState<Content>(defaultContent); const [mode,setMode]=useState<Mode>('home');
 const [seconds,setSeconds]=useState(10); const [done,setDone]=useState(false); const [step,setStep]=useState(1); const [fingerSeconds,setFingerSeconds]=useState(10); const video=useRef<HTMLVideoElement>(null); const stream=useRef<MediaStream|null>(null);
 useEffect(()=>{try{const v=localStorage.getItem(KEY);if(v)setContent(JSON.parse(v))}catch{}},[]);
 useEffect(()=>{if(mode!=='face'||done)return; const t=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(t);setDone(true);return 0}return s-1}),1000);return()=>clearInterval(t)},[mode,done]);
 useEffect(()=>{if(mode!=='finger'||done)return;const t=setInterval(()=>setFingerSeconds(s=>{if(s<=1){if(step===5){clearInterval(t);setDone(true);return 0}setStep(x=>x+1);return 10}return s-1}),1000);return()=>clearInterval(t)},[mode,done,step]);
 useEffect(()=>{if(mode==='face'&&!done){navigator.mediaDevices?.getUserMedia({video:true}).then(s=>{stream.current=s;if(video.current)video.current.srcObject=s}).catch(()=>{})}return()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null}},[mode,done]);
 const home=()=>{stream.current?.getTracks().forEach(t=>t.stop());setMode('home');setDone(false);setSeconds(10);setStep(1);setFingerSeconds(10)};
 if(mode==='face')return <main className="page"><section className="shell"><button className="back" onClick={home}>← Back</button><div className="scan"><h1>{content.face.title}</h1><p>{content.face.instruction}</p><div className="camera"><video ref={video} autoPlay muted playsInline/><div className="face-ring"/></div>{!done?<><b>{content.face.scanning}</b><div className="timer">{seconds}s</div><div className="bar"><i style={{width:`${(10-seconds)*10}%`}}/></div></>:<><b className="success">{content.face.success}</b><div className="actions"><button onClick={home}>{content.face.close}</button><button className="secondary" onClick={()=>{setDone(false);setSeconds(10)}}>{content.face.retry}</button></div></>}</div></section></main>;
 if(mode==='finger')return <main className="page"><section className="shell"><button className="back" onClick={home}>← Back</button><div className="scan"><h1>{content.finger.title}</h1><p>{content.finger.instruction}</p><div className="fingerprint">◎</div>{!done?<><b>{content.finger.progress.replace('{current}',String(step)).replace('{total}','5')}</b><div className="timer">{fingerSeconds}s</div><div className="bar"><i style={{width:`${((step-1)*20+(10-fingerSeconds)*2)}%`}}/></div></>:<><b className="success">{content.finger.success}</b><div className="actions"><button onClick={home}>{content.finger.close}</button><button className="secondary" onClick={()=>{setDone(false);setStep(1);setFingerSeconds(10)}}>{content.finger.retry}</button></div></>}</div></section></main>;
 return <main className="page"><section className="home"><h1>{content.home.title}</h1><p>{content.home.subtitle}</p><div className="options"><button onClick={()=>{setMode('face');setDone(false);setSeconds(10)}}><span>◉</span><strong>{content.home.faceButton}</strong><small>10 second scan</small></button><button onClick={()=>{setMode('finger');setDone(false);setStep(1);setFingerSeconds(10)}}><span>◎</span><strong>{content.home.fingerprintButton}</strong><small>5 capture steps</small></button></div><footer>{content.home.footer}</footer><a className="admin-link" href="/admin">Admin</a></section></main>
}
